### ISSUE TITLE
Acordion Faqs

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-civitech#115]
Preguntan si es posible que la FAQ se cierre cuando haces click sobre si mismo? Ahora mismo solo se cierra un tab cuando haces click en otro.

**Comment by marceltectonica** [comment]
https://clever-belekoy-d45eb9.netlify.app/faq/

**Comment by RodrigoLeonMdp** [comment]
Es posible! ya hago los cambios

**Comment by RodrigoLeonMdp** [comment]
Solucionado aqui: https://github.com/Tectonica-Campaigns-Solutions/ga-civitech/pull/116
