### ISSUE TITLE
Buscar solucion active path

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-civitech#73]
Poder marcar como activo el punto de menu donde estamos

**Comment by marceltectonica** [comment]
Hola, he pensado una soluicion para detectar los puntos de menu activos.  He añadido en page.js una clase que es el id de la pagina. 'pale-gray wrap-page DatoCmsPage-90552654'

Y en el menu principal he añadido a cada <li> la clase de la página. La idea seria añadir a los enlaces de segundo nivel del menu principal tb su referencia a la pagina

Luego con un useffect dentro de navbar.js pedir el id de la pagina actual:

const pageId = document.querySelector('.wrap-page').classList;

Y recorrer todo el menu principal buscando un elemento con ese mismo id y añadirle la clase active

**Comment by RodrigoLeonMdp** [comment]
@marceltectonica Cree una posible solucion en el siguiente PR: https://github.com/Tectonica-Campaigns-Solutions/ga-civitech/pull/75
