### ISSUE TITLE
Link como button en menu footer

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-civitech#78]
He añadido un menu item como is button en el footer pero no se comporta correctamente:

![Captura de pantalla 2023-02-13 a las 8 02 18](https://user-images.githubusercontent.com/110401825/218392112-932597ea-f075-4b1a-af03-b39cc1da3d4c.png)

Deberia ser así:

![Captura de pantalla 2023-02-13 a las 8 02 42](https://user-images.githubusercontent.com/110401825/218392185-80384a5d-d554-4784-96c7-9c198b6e1b76.png)

**Comment by RodrigoLeonMdp** [comment]
Solucionado! La redireccion ya funciona: 
![image](https://user-images.githubusercontent.com/112974289/218505049-642b47db-5829-4b72-b3b3-d49f3621b596.png)
