### ISSUE TITLE
Buscar una solución para los h1 y h2 de las paginas

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-civitech#79]
Cada pàgina deberia tener como minimo un h1. 

De momento si se usa el hero, el titulo dentro del narrative block deberia ser h1, en lugar de h2. 

Por ejemploe aqui:

https://main--clever-belekoy-d45eb9.netlify.app/product/campaigns-os/

![Captura de pantalla 2023-02-13 a las 8 05 21](https://user-images.githubusercontent.com/110401825/218392696-da3e05f1-ab5b-4760-a61f-0c392dd96f64.png)

Esto deberia ser H1.

**Comment by RodrigoLeonMdp** [comment]
Solucionado en el sig. PR: https://github.com/Tectonica-Campaigns-Solutions/ga-civitech/pull/85
