### ISSUE TITLE
Soporte titulo de pagina en paginas sin hero activado

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-civitech#81]
Hay paginas como faq 

https://clever-belekoy-d45eb9.netlify.app/faq/

Donde no tenemos hero definido, pero habria que pintar como mínimo el titulo de la pagina como H1.

**Comment by RodrigoLeonMdp** [comment]
Solucionado en el sig. PR: https://github.com/Tectonica-Campaigns-Solutions/ga-civitech/pull/85

**Comment by marceltectonica** [comment]
Hola @RodrigoLeonMdp 

No me convence demasiado la solucion que tenemos del use H1 en los bloques narrativos.. 

Si cren una pagina sin bloque narrativo los obligamos a añadirla. Mirate a ver si podriamos mover los padding top a nivel de <main> solo para los modelos page. Y quitaria el padding top en los narrative blocks. Usaria el campo title de la pagina como titulo cuando no este activado el 'show hero' como teniamos antes. 

La idea seria que si creo una pagina vacia como minimo muestre el H1 y que no este por debajo del menu fijo.
