### ISSUE TITLE
Bloques embed

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-civitech#92]
He separado los embed en dos bloques de datocms, video e iframe. 

Mirate el de video, se puede añadir en pagina y tb en contendio de post. Deberiamos pensar como hacerlo centrado

**Comment by marceltectonica** [comment]
Te dejo aqui url de pagina con los dos embeds añadidos:

https://clever-belekoy-d45eb9.netlify.app/test-embeds/

**Comment by RodrigoLeonMdp** [comment]
En el sig. pr https://github.com/Tectonica-Campaigns-Solutions/ga-civitech/pull/93 centre los embed: 
![image](https://user-images.githubusercontent.com/112974289/219033202-a376c469-3fde-4658-b57f-872a6b202bee.png)
![image](https://user-images.githubusercontent.com/112974289/219033286-f42ac1e8-9f15-40cf-9dff-c933eeabaefa.png)
