### ISSUE TITLE
Revisar estilo de h1 cuando es pagina sin hero

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-civitech#97]
Yo el H1 cuando es pagina sin hero lo haria con la misma fuente y tamaño que cuando es h1 en hero

**Comment by RodrigoLeonMdp** [comment]
Solucionado aqui: https://github.com/Tectonica-Campaigns-Solutions/ga-civitech/pull/100/commits/9a56e7fc33d080707303478a652455cdac266171
