### ISSUE TITLE
Grid stats

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-civitech#99]
El grid stats lo voy a tener que usar en unas pagina concretas añadiendo descripcion

No me acaba de gustar como se ve

https://clever-belekoy-d45eb9.netlify.app/impact-report-2020/

Revisaria espaciado, cuidado como afecta a las otras paginas. 

Yo el margin del h2 lo reduciria y pondria margin top a los stats en si y centraria la descripcion.

**Comment by RodrigoLeonMdp** [comment]
Genial! Adjunto captura del nuevo resultado, podemos seguir cambiandolo si no nos convence: 

![image](https://user-images.githubusercontent.com/112974289/219634399-af9ee3bb-cba1-455c-a13e-2e41b4dc71c5.png)
